### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Anonymous0064** [NaveenDA/naveenda.github.io#16]
How make Dark and Light Mode?? I am newbie snd just want to know for learning. Help me

**Comment by NaveenDA** [comment]
Basically, you need two sets of stylesheets (lightmode.css and darkmode.css). When the dark mode is enabled, add a class on body tag and change the style from `lightmode.css` to `darkmode.css`

**Comment by Anonymous0064** [comment]
Thanks sir!! Can you help me by adding it in www.github.com/Anonymous0064/testsite?? Please. I am inviting you as collaborator.
